Feature/mermaid 11.2.1, Node 20 and Ubuntu 22.04
NewTec-GmbH/gitWorkInstructions pull request #4
Opened 2024-10-09 13:50 UTC by nhjschulz

Upgraded to newer version of sphinx and downgraded from ubuntu-latest to ubuntu-22.04

Ubuntu latest (24.04) fails in sphinx build due to security settings around launching chrome.
NPM packages reported warnings to to outdated packages and vulnerabilities.

2024-10-09 16:03 UTC, BlueAndi requested changes

2024-10-09 16:03 UTC, BlueAndi commented on doc/versioning/images/Components.png
Do we mix between PlantUML and EA?

2024-10-10 06:57 UTC, nhjschulz commented on doc/versioning/images/Components.png
Will replace it with plantUML in next commit.

2024-10-10 08:49 UTC, BlueAndi approved these changes

2024-10-10 14:01 UTC, merged